name: pull-request
on: pull_request

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Build & Export
        run: npm run export:staging
      - uses: FirebaseExtended/action-hosting-deploy@v0.3-alpha
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_CHANNEL_DEPLOY_SERVICE_ACCOUNT }}"
          projectId: staging
          expires: 14d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
